language: node_js
node_js:
  - "0.8"

install:
  - "cd .."
  - "git clone git://github.com/xtuple/xtuple.git --recursive"
  - "cd xtuple"
  - "bash scripts/install_xtuple.sh -ipn"
  - "cp test/lib/login_data.js ../xtuple-extensions/test/lib/login_data.js"
  - "cd ../xtuple-extensions"
  - "npm install"
  - "npm run-script test-build"
  - "mv sample/xtuple-ice-cream source"
  - "mkdir -p test/xtuple-ice-cream/specs"
  - "cp source/xtuple-ice-cream/test/* test/xtuple-ice-cream/specs"
  - "../xtuple/scripts/build_app.js -e source/xtuple-ice-cream"
  - "psql -d dev -U admin -c \"select xt.js_init();insert into xt.usrext (usrext_usr_username, usrext_ext_id) select 'admin', ext_id from xt.ext where ext_name = 'icecream';\""
  - "psql -d dev -U admin -c \"select xt.js_init();insert into usrpriv (usrpriv_username, usrpriv_priv_id) select 'admin', priv_id from priv where priv_name = 'MaintainIceCreamFlavors';\""
  

before_script:
  - "cd ../xtuple/node-datasource"
  - "node main.js &"
  - "sleep 10"
  - "cd .."

script:
  - "npm run-script test"
  - "npm run-script test-datasource"
  - "cd ../xtuple-extensions"
  - "npm run-script test"
  - "../xtuple/node_modules/.bin/jshint source"
